name: Deploy to Windows Dev

on:
    pull_request:
        types: [closed]
        branches:
            - dev

jobs:
    windows-deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                  ref: dev
            - uses: actions/setup-node@v1
            - run: npm install
            - run: npm run bundle
            - name: Copy folder content recursively to remote
            uses: garygrossgarten/github-action-scp@release
            with:
                      local: 'deploy/'
                      remote: 'c:/nodeapps/tutor-backend'
                      dotfiles: true
                      rmRemote: true
                      privateKey : ${{ secrets.DEV_WIN_SERVER_SSH_KEY }}
                      host: 'tutorschedulingdev.oc.edu'
                      username: 'david.north'
  
            - name: Deploy to Server
              uses: easingthemes/ssh-deploy@v2.1.1
              env:
                  SSH_PRIVATE_KEY: ${{ secrets.DEV_WIN_SERVER_SSH_KEY }}
                  ARGS: '-rltgoDzvO --delete'
                  SOURCE: 'deploy/'
                  REMOTE_HOST: 'tutorschedulingdev.oc.edu'
                  REMOTE_USER: david.north
                  TARGET: 'c:/nodeapps/tutor-backend'
            - name: Execute SSH commmands on remote server
              uses: JimCronqvist/action-ssh@master
              env:
                  NAME: 'Root'
              with:
                  hosts: 'david.north@tutorschedulingdev.oc.edu'
                  privateKey: ${{ secrets.DEV_WIN_SERVER_SSH_KEY }}
                  debug: false
                  command: |
                      cd c:/nodeapps/tutor-backend
                      npm install

