name: Deploy to Windows Dev

on:
    pull_request:
        types: [closed]
        branches:
            - dev

jobs:
    windows-deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                  ref: dev
            - uses: actions/setup-node@v1
            - run: npm install
            env:
                  DB_HOST: ${{ secrets.DEV_DB_HOST }}
                  DB_PW: ${{ secrets.DEV_DB_PW}}
                  DB_USER: ${{ secrets.DEV_DB_USER }}
                  DB_NAME: ${{ secrets.DEV_DB_NAME }}
                  TWILIO_ACCOUNT_SID : ${{TWILIO_ACCOUNT_SID}}
                  TWILIO_AUTH_TOKEN1 : ${{TWILIO_AUTH_TOKEN2}}
                  TWILIO_AUTH_TOKEN2 :  ${{TWILIO_AUTH_TOKEN2}}
                  TWILIO_NUMBER :${{TWILIO_NUMBER}}
            - run: |
                    touch .env
                    echo db_host="$DB_HOST" >> .env
                    echo db_pw="$DB_PW" >> .env
                    echo db_user="$DB_USER" >> .env
                    echo db_name="$DB_NAME" >> .env
                    echo twilio_acount_sid="$TWILIO_ACCOUNT_SID" >> .env
                    echo twilio_auth_token1="$TWILIO_AUTH_TOKEN1" >> .env
                    echo twilio_auth_token2="$TWILIO_AUTH_TOKEN2" >> .env
                    echo twilio_number="$TWILIO_NUMBER" >> .env
            - run: npm run bundle

            - name: Copy folder content recursively to remote
              uses: garygrossgarten/github-action-scp@release
              with:
                  local: deploy/
                  remote: c:/nodeapps/tutor-backend
                  recursive : true
                  host: 'tutorschedulingdev.oc.edu'
                  username: 'david.north'
                  privateKey: ${{ secrets.DEV_WIN_SERVER_SSH_KEY  }}
                  password: ${{ secrets.PASSWORD }}

            - name: Commands via ssh
              uses: fifsky/ssh-action@master
              with:
                command: |
                  cd /nodeapps/tutor-backend
                  npm install

                host: ${{ secrets.HOST }}
                user: root
                key: ${{ secrets.PRIVATE_KEY}}

