name: Deploy to Windows Dev

on:
    pull_request:
        types: [closed]
        branches:
            - dev

jobs:
    windows-deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                  ref: dev
            - uses: actions/setup-node@v1
            - run: npm install
            - run: npm run bundle

            - name: copy file via ssh key
            uses: appleboy/scp-action@master
            with:
              host: 'tutorschedulingdev.oc.edu'
              username: 'david.north'
              port: '22'
              key: ${{ secrets.DEV_WIN_SERVER_SSH_KEY  }}
              source: 'deploy/'
              target: 'c:/nodeapps/tutor-backend'

            - name: Execute SSH commmands on remote server
              uses: JimCronqvist/action-ssh@master
              env:
                    NAME: 'Root'
              with:
                    hosts: 'david.north@tutorschedulingdev.oc.edu'
                    privateKey: ${{ secrets.DEV_WIN_SERVER_SSH_KEY }}
                    debug: false
                    command: |
                        cd c:/nodeapps/tutor-backend
                        npm install

